import "~/styles/globals.css";

import type { Metadata } from "next";
import { Geist } from "next/font/google";

import { TRPCReactProvider } from "~/trpc/react";
import { ThemeProvider } from "./_components/theme-provider";
import { ToastProvider } from "~/components/ui/toast-provider";

export const metadata: Metadata = {
	title: "Théo Afrique",
	description: "Generated by create-t3-app",
	icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const geist = Geist({
	subsets: ["latin"],
	variable: "--font-geist-sans",
});

export default function RootLayout({
	children,
}: Readonly<{ children: React.ReactNode }>) {
	return (
		<html
			lang="fr"
			suppressHydrationWarning
			className={`${geist.variable} scroll-smooth`}
		>
			<body>
				<ThemeProvider
					attribute="class"
					defaultTheme="system"
					enableSystem
					disableTransitionOnChange
				>
					<ToastProvider>
						<TRPCReactProvider>{children}</TRPCReactProvider>
					</ToastProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
